### All components for a full IRIS Installation

services:
  ### ------------------------------------------
  ###             IRIS Services
  ### ------------------------------------------

  ### Frontend service
  IRIS-frontend:
    image: ghcr.io/faecher/iris-frontend:latest
    container_name: IRIS-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - IRIS-backend
    networks:
      - IRIS-network
    environment:
      - BACKEND_HOSTNAME=IRIS-backend
      - BACKEND_PORT=8000
      - TILES_HOST=IRIS-versatiles
      - TILES_PORT=8080

  ### Backend service
  IRIS-backend:
    image: ghcr.io/faecher/iris-backend:latest
    container_name: IRIS-backend
    restart: unless-stopped
    volumes:
      - IRIS-data:/data ### TODO: do we need this? isn't this only for an sqlite db? could that be offloaded into the pgsql that we host anyway?
    networks:
      - IRIS-network
    environment:
      - DATA_PATH=/data

  ### ------------------------------------------
  ###           Offline-Maps server
  ### ------------------------------------------
  IRIS-versatiles:
    image: versatiles/versatiles-frontend:latest-alpine  # with frontend
    container_name: IRIS-versatiles
    restart: unless-stopped
    volumes:
      - ${PWD}:/data:ro ### mount the current directory as read-only for map data
    command: ${VERSATILES_FILE:-tiles.versatiles}
    networks:
      - IRIS-network



  # TODO: add pgsql and chirpstack services
  # Chirpstack: https://github.com/chirpstack/chirpstack-docker/blob/master/docker-compose.yml
  # we use http push, so so mqtt is not needed



volumes:
  IRIS-data:
    driver: local
  versatiles-data:
    driver: local

networks:
# TODO: do we want to separate nginx and backend networks?
  IRIS-network:
    driver: bridge