### All components for a full IRIS Installation
# Commented out env vars are examples of additional configuration options that can be set with their default values.

secrets:
  iris_db_password:
    name: iris_db_password
    external: true
  postgres_db_password:
    external: true
  chirpstack_db_password:
    external: true

  

services:
  ### ------------------------------------------
  ###             IRIS Services
  ### ------------------------------------------

  ### Frontend service
  IRIS-frontend:
    image: ghcr.io/faecher/iris-frontend:latest
    ports:
      - "${FRONTEND_PORT:-80}:80"
    networks:
      - IRIS-network
    environment:
      BACKEND_HOSTNAME: IRIS-server
      BACKEND_PORT: 8080
      TILES_HOST: versatiles
      TILES_PORT: 8080
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 5s
        order: stop-first

  ### Backend service
  IRIS-server:
    image: ghcr.io/faecher/iris-server:latest
    ports:
      - "8080:8080"
    secrets:
      - iris_db_password
    networks:
      - IRIS-network
    environment:
      # SERVER_ADDRESS: "0.0.0.0" # Port is 8080
      # SERVER_READ_TIMEOUT: 10 # seconds
      # SERVER_WRITE_TIMEOUT: 10 # seconds
      # SERVER_IDLE_TIMEOUT: 2 # minutes
      # SERVER_MAX_HEADER_BYTES: 1048576 # 1 MB

      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: iris
      # DB_PASSWORD: iris # Will be preferred over DB_PASSWORD_FROM_FILE if both are set
      DB_PASSWORD_FROM_FILE: /run/secrets/iris_db_password
      # DB_NAME: iris
      # DB_SSLMODE: disable
      DB_MAX_RETRIES: 5
      # DB_RETRY_INTERVAL: 5

      # MCP_RESOURCE_UPDATE: 5 # MCP resource update interval in seconds

      # If Auth-Token is set, the token will take priority over email/password for authentication.
      # TRACCAR_HOST: http://localhost:80
      # TRACCAR_EMAIL: testmail@test.com
      # TRACCAR_PASSWORD: 123456
      # TRACCAR_AUTH_TOKEN: 1234 
      # TRACCAR_AUTH_TIMEOUT: 10
    deploy:
      replicas: 1 # Currently not verified to work with multiple replicas
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 5s
        order: stop-first


  ### ------------------------------------------
  ###             PostgreSQL server
  ### ------------------------------------------
  postgres:
    image: postgres:18-alpine
    secrets:
      - postgres_db_password
      - iris_db_password
      - chirpstack_db_password
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_db_password
    networks:
      - IRIS-network
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d:ro
      - pgsql-data:/var/lib/postgresql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  ### ------------------------------------------
  ###           Offline-Maps server
  ### ------------------------------------------
  versatiles:
    image: versatiles/versatiles-frontend:latest-alpine  # with frontend
    volumes:
      - ${PWD}:/data:ro ### mount the current directory as read-only for map data
    command: ${VERSATILES_FILE:-tiles.versatiles}
    networks:
      - IRIS-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure



volumes:
  pgsql-data:
    driver: local
  versatiles-data:
    driver: local

networks:
  IRIS-network:
    driver: overlay