name: Build the app

on:
  push:

jobs:
  build-frontend:
    name: Build IRIS Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=docker,dest=/tmp/image.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-image
        path: /tmp/image.tar
        retention-days: 1